---
- name: Configure Strongswan strongswan.conf
  template:
    src: strongswan.conf.j2
    dest: "{{ strongswan_conf_file }}"
    owner: root
    group: root
    mode: 0644
  when: strongswan_settings is defined

- name: Configure Strongswan updown script
  template:
    src: updown.sh.j2
    dest: "{{ strongswan_swanctl_updown_file }}"
    owner: root
    group: root
    mode: 0755
  notify:
    - swanctl restart

- name: Ensure Strongswan service is enabled and started
  systemd:
    name: "{{ strongswan_swanctl_svc }}"
    state: started
    enabled: yes
    daemon_reload: yes

- name: Configure Strongswan connections
  template:
    src: swanctl.conf.j2
    dest: "{{ item.name }}"
    owner: root
    group: root
    mode: 0644
  loop: "{{ strongswan_conn_list }}"
  notify:
    - swanctl loadconn