---
- include_tasks: install.yml

- include_tasks: disable_starter.yml

- include_tasks: apparmor.yml

- include_tasks: letsencrypt.yml
  when: strongswan_letsencrypt_enable is true

- include_tasks: config.yml
