---
- name: Restart strongswan
  systemd:
    name: strongswan
    state: restarted
    daemon_reload: yes
  when: ansible_service_mgr == 'systemd'

- name: Reload swanctl
  command: swanctl --load-all
  listen: reload swanctl
  register: reload_result
  changed_when: reload_result.rc == 0
  failed_when: reload_result.rc != 0
