---
- name: swanctl restart
  systemd:
    name: "{{ strongswan_swanctl_svc }}"
    state: restarted

- name: swanctl loadconn
  command: swanctl --load-conns

- name: systemctl daemon-reload
  systemd:
    daemon_reload: yes
